export const ROUTES = {
  LOGIN: "/login",
  HOME: "/",
  PLATFORM: "/platform",
  SOLUTIONS: "/solutions",
  PAYMENTPOSTING: "/solutions/payment-posting",
  LOCKBOXANALYSIS: "/solutions/lockbox",
  DENIALWORKFLOW: "/solutions/denials",
  PREBILLSERVICES: "/solutions/pre-bill",
  CONTRACTANALYSIS:"/solutions/contract-analysis",
  ELIGIBILITYDISCOVERY:"/solutions/eligibility",
  ABOUTUS: "/about-us",
  RESOURCES: "/resources",
  CONTACTUS: "/contact-us",
  RCMREADINESS:'/rcm-readines',
  TERMSCONDITIONS:'/terms',
  PRIVACYPOLICY:"/privacy-policy",
  FAQ:"/faq",
  REQUEST_DEMO: "/request-demo",
  NOT_FOUND: "*",
};

