export const ROUTES = {
  LOGIN: "/login",
  HOME: "/",
  PLATFORM: "/platform",
  SOLUTIONS: "/solutions",
  PAYMENTPOSTING: "/solutions/payment-posting",
  LOCKBOXANALYSIS: "/solutions/lockbox",
  DENIALWORKFLOW: "/solutions/denials",
  PREBILLSERVICES: "/solutions/pre-bill",
  CONTRACTANALYSIS:"/solutions/contract-analysis",
  ELIGIBILITYDISCOVERY:"/solutions/eligibility",
  ELIGIBILITY_VERIFICATION_SEO: "/eligibility-verification-and-denial-management-ai-automation",
  HEALTHCARE_DOCUMENT_MANAGEMENT_SEO: "/healthcare-document-management-with-generative-ai",
  BEHAVIORAL_HEALTH_RCM_SEO: "/behavioral-health-rcm-with-generative-ai",
  REVENUE_CYCLE_MANAGEMENT_SEO: "/revenue-cycle-management-with-ai-powered-solutions",
  CASH_POSTING_AUTOMATION_SEO: "/streamline-your-cash-posting-with-automation-solutions",
  MEDICAL_BILLING_SERVICES_SEO: "/ai-driven-medical-billing-services-for-enhanced-revenue-cycle-management",
  HEALTHCARE_BACK_OFFICE_SEO: "/healthcare-back-office-with-advanced-ai-solutions",
  RCM_AI_BILLING_SERVICES_SEO: "/rcm-ai-powered-billing-services",
  HEALTHCARE_CLAIMS_PROCESSING_SEO: "/healthcare-claims-processing-with-ai-automation",
  SPECIALTY_MEDICAL_BILLING_SEO: "/specialty-medical-billing-with-generative-ai-rcm",
  ABOUTUS: "/about-us",
  RESOURCES: "/resources",
  CONTACTUS: "/contact-us",
  RCMREADINESS:'/rcm-readines',
  TERMSCONDITIONS:'/terms',
  PRIVACYPOLICY:"/privacy-policy",
  FAQ:"/faq",
  REQUEST_DEMO: "/request-demo",
  BLOG_DETAIL: "/resource/:slug",
  MEDIA_DETAIL: "/media/:slug",
  NOT_FOUND: "*",
};

